---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: viewer
rules:
- apiGroups:
  - "*"
  resources:
  - pods
  - services
  - endpoints
  - events
  - configmaps
  - secrets
  - namespaces
  verbs:
  - get
  - list
  - watch